app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("the_list.urls", namespace="product")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

the_list/urls.py
from django.urls import path
from .views import (index, product_change, product_remove, product_add,
                    product_change_status, clean_user_products_full)

app_name = "the_list"


urlpatterns = [
    path('', index, name='list_products'),
    path('history/clean_history/', clean_user_products_full, name='product_history_clean'),
    path('search/', index, name='search'),

    path('product-add/', product_add, name='product_add'),
    path('product_change/<slug:product_slug>/', product_change, name='product_change'),
    path('product_change_status/<slug:product_slug>/', product_change_status, name='product_change_status'),
    path('product_delete/<slug:product_slug>/', product_remove, name='product_remove'),
]

the_list/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class WaitObjManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Products.Status.WAIT)


class Products(models.Model):

    class Status(models.TextChoices):

        PURCHASED = 'PU', 'purchased'
        WAIT = 'WA', 'wait'

    name = models.CharField(max_length=155)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to='purchases_images', blank=True, null=True)
    price = models.DecimalField(default=0.00, max_digits=9, decimal_places=2, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    session_key = models.CharField(max_length=32, null=True, blank=True)
    buy_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.WAIT)

    objects = models.Manager()
    waitobj = WaitObjManager()

    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'
        ordering = ('-created',)
        indexes = [
            models.Index(fields=['-created']),
        ]

    def get_absolute_url(self):
        return reverse("product:product_remove", kwargs={"product_slug": self.slug})

    def __str__(self):
        return f'Продукт {self.name} | '

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            unique_slug = f"{base_slug}-{uuid.uuid4().hex[:6]}"
            self.slug = unique_slug

        super().save(*args, **kwargs)

the_list/forms.py
from django import forms
from .models import Products


class ProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['name', 'price', 'description', 'image']


class ProductFilterForm(forms.Form):
    min_price = forms.DecimalField(label='Минимальная цена', required=False)
    max_price = forms.DecimalField(label='Максимальная цена', required=False)
    start_date = forms.DateField(label='Дата начала', required=False)
    end_date = forms.DateField(label='Дата окончания', required=False)

the_list/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from the_list.forms import ProductsForm
from the_list.models import Products
from the_list.utils import get_user_index_products, get_history_products, q_search, filter_products


def index(request):
    query = request.GET.get('q', None)
    history = request.GET.get('history', None)
    filter = request.GET.get('filter', None)

    if history:
        products = get_history_products(request).order_by('-buy_date')
    else:
        products = get_user_index_products(request)

    last_products = products[:3]

    if query:
        products = q_search(query, products)

    if filter:
        products = filter_products(request, products)

    order_by_list = request.GET.getlist('order_by')
    valid_fields = [field.name for field in Products._meta.get_fields()]
    valid_order_by_list = [field for field in order_by_list if field in valid_fields]
    if valid_order_by_list:
        products = products.order_by(*valid_order_by_list)


    paginator = Paginator(products, 8)
    page_number = request.GET.get('page', 1)
    try:
        current_page = paginator.page(page_number)
    except PageNotAnInteger:
        current_page = paginator.page(1)
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)

    total_price_waiting = Products.waitobj.all().aggregate(Sum('price'))['price__sum']
    total_price_purch = Products.objects.filter(status=Products.Status.PURCHASED).aggregate(Sum('price'))['price__sum']
    context = {
        'products': current_page,
        'last_products': last_products,
        'all_wait_product': get_user_index_products(request).count(),
        'count_history_products': get_history_products(request).count(),
        'total_price_waiting': total_price_waiting if total_price_waiting else 0,
        'total_price_purch': total_price_purch if total_price_purch else 0,
        'history': history,
    }
    if history:
        return render(request, 'the_list/list_history.html', context)
    return render(request, 'the_list/index.html', context)


def product_add(request):
    if request.method == 'POST':
        form = ProductsForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            if not request.session.session_key:
                request.session.create()
            form.instance.session_key = request.session.session_key
            form.save()

            messages.success(
                request, "Вы успешно добавили покупку"
            )
            return redirect("product:list_products")
    else:
        form = ProductsForm()

    return render(request, 'the_list/index.html', {'form': form})


def product_change(request, product_slug):
    product = get_object_or_404(Products, slug=product_slug)
    if request.method == "POST":
        form = ProductsForm(data=request.POST, files=request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(
                request, f"Вы успешно изменили покупку"
            )
            return HttpResponseRedirect(request.META['HTTP_REFERER'])

    else:
        form = ProductsForm(instance=product)

    context = {
        'form': form,
    }
    return render(request, 'the_list/index.html', context)


def product_remove(request, product_slug):
    product = Products.objects.get(slug=product_slug)
    product.delete()

    messages.success(
        request, f"Вы успешно удалили покупку"
    )
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def clean_user_products_full(request):
    products = get_history_products(request)
    products.delete()

    messages.success(
        request, f"Вы успешно удалили всю историю"
    )
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def product_change_status(request, product_slug):
    status = Products.Status.PURCHASED
    product = Products.waitobj.get(slug=product_slug)
    product.status = status
    product.save()

    messages.success(
        request, f"Покупка была успешно перенесена в историю покупок"
    )

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

templates/base.html
{% load static %}
{% load products_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/my_css.css' %}">

  <title>The products list</title>
</head>


<body>
<header>
  <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid text">
      <a class="navbar-brand hov text-white" href="{% url 'product:list_products' %}">Список покупок</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link hov text-white"
               aria-current="page"
               href="{% url 'product:list_products' %}?history=True">
              Полная история</a>
          </li>

          <!--          Сортировка-->
          <li class="nav-item dropdown">
            <a class="nav-link hov dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
               aria-expanded="false">
              Сортировка покупок
            </a>
            <!--            форм сорт-->
            <form action="" method="get" class="dropdown-menu custom-shadow rounded">
              {% if history %}
                <input type="hidden" name="history" value="True">
              {% endif %}
              <p class="mx-1 mt-1">Сортировать по:</p>

              <hr class="dropdown-divider mx-3">

              <div class="form-check p-1">
                <p class="mx-1 mt-1">Цене:</p>
                <select class="form-select" name="order_by">
                  <option value="empty_field"> --------- </option>
                  <option value="price">Цена (по возрастанию)</option>
                  <option value="-price">Цена (по убыванию)</option>
                </select>
              </div>

              <div class="form-check p-1">
                <p class="mx-1 mt-1">Дате:</p>
                <select class="form-select" name="order_by">
                  <option value="empty_field"> --------- </option>
                  <option value="created">Дате (по возрастанию)</option>
                  <option value="-created">Дате (по убыванию)</option>
                </select>
              </div>

              <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>

            </form>
            <!--            конец формы сорт-->
          </li>
          <!--          конец сортировки-->

          <!--          Фильтры-->
          <li class="nav-item dropdown">
            <a class="nav-link hov dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
               aria-expanded="false">
              Фильтры
            </a>
            <!--            форм фильтр-->
            <form action="" method="get" class="dropdown-menu custom-shadow rounded p-1">
              {% if history %}
                <input type="hidden" name="history" value="True">
                <input type="hidden" name="filter" value="True">
              {% else %}
                <input type="hidden" name="filter" value="True">
              {% endif %}
              <p class="mx-1 mt-1">Фильтровать по:</p>

              <hr class="dropdown-divider mx-3">

              <div class="mb-3">
                <label for="min_price" class="form-label">Мин цена:</label>
                <input type="number" class="form-control" id="min_price" name="min_price">
              </div>

              <div class="mb-3">
                <label for="max_price" class="form-label">Макс цена:</label>
                <input type="number" class="form-control" id="max_price" name="max_price">
              </div>

              <div class="mb-3">
                <label for="start_date" class="form-label">Начальная дата:</label>
                <input type="date" class="form-control" id="start_date" name="start_date">
              </div>

              <div class="mb-3">
                <label for="end_date" class="form-label">Конечная дата:</label>
                <input type="date" class="form-control" id="end_date" name="end_date">
              </div>

              <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>

            </form>
            <!--            конец формы фильтр-->
          </li>
          <!--          конец фильтры-->
        </ul>

<!--        кнопка поиска-->
        <form class="d-flex mx-auto" role="search" action="{% url 'product:search' %}" method="get">
          {% if history %}
            <input type="hidden" name="history" value="True">
          {% endif %}
          <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

      </div>

    </div>
  </nav>
</header>


<section>
  <div class="container-fluid">

<!--    оповещение ошибок формы-->
    {% include 'the_list/form_eror.html' %}
<!--    конец оповещения ошибок формы-->

    <!--    всплывающее сообщение-->
    {% include 'the_list/messages.html' %}
    <!--    конец сообщения-->

    <!--    разделение на лев/прав-->
    <div class="row align-items-start">

      <!--      левая часть экрана-->
      <div class="col-md-6 m-3 p-3 custom-shadow rounded" style="max-height: calc(100vh - 170px); overflow-y: auto;">

        {% block main %}
        <!--        список продуктов / история-->
        {% endblock %}

        <!--    пагинация-->
        <div class="row">
          {% if products %}
          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center my-4">
              <div class="custom-shadow d-flex">

                <li class="page-item {% if not products.has_previous %}disabled{% endif %} ">
                  <a class="page-link"
                     href="{% if products.has_previous %}?{% change_params page=products.previous_page_number %}{% else %}#{% endif %}">Назад</a>
                </li>

                {% for page in products.paginator.page_range %}
                {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
                <li class="page-item {% if products.number == page %} active {% endif %}">
                  <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                </li>
                {% endif %}
                {% endfor %}

                <li class="page-item {% if not products.has_next %}disabled{% endif %} ">
                  <a class="page-link"
                     href="{% if products.has_next %}?{% change_params page=products.next_page_number %}{% else %}#{% endif %}">Вперед</a>
                </li>

              </div>
            </ul>
          </nav>
          {% endif %}
        </div>
        <!--    конец пагинации-->

      </div>
      <!--      конец левой части экрана-->


      <!--        правая часть экрана-->
      <div class="col-md-5 d-flex flex-column justify-content-between">
        <!--        1 левый блок-->
        <div class="row m-3 p-3 custom-shadow rounded">
          <div class="col-md-7 border-end ">
            <h4>Стата</h4>
            {% with products.count as total_pr %}
            <p>Всего ожидающих покупок - {{ all_wait_product }}</p>
            <p>Общая стоимость ожидающих покупок - {{ total_price_waiting|truncatechars:9 }}</p>
            <p>Общая стоимость купленных - {{ total_price_purch|truncatechars:11 }}</p>
            <p>Всего купленных - {{ count_history_products }}</p>
            {% endwith %}
          </div>

          <div class="col-md-5">

            <h4>Последнее добавленное</h4>

            <div class="list-group">
              {% if last_products %}
                {% for p in last_products %}
                <a href="#" class="list-group-item list-group-item-action"
                data-bs-toggle="modal" data-bs-target="#productDetailModal{{ p.id }}">
                  {{ p.name|truncatechars:15 }}
                  <small>цена: {{ p.price }}</small>
                </a>
                {% endfor %}
              {% else %}
                <h3>Нету купленных</h3>
              {% endif%}
            </div>
          </div>

        </div>
        <!--        конец 1 левого блока-->

        <!--        2 левый блок-->
        <div class="row m-3 p-3 custom-shadow rounded" style="margin-top: auto;">
          <!--            форма добавления покупки-->
          {% include 'the_list/product_add.html' %}
          <!--          конец форма добавления покупки-->
        </div>
        <!--        конец 2 левого блока-->
      </div>
      <!--      конец правой части экрана-->

    </div>

  </div>

</section>

<footer class="py-4 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright copy bla bla 2024</p>
  </div>
</footer>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'js/message.js' %}"></script>

</body>
</html>

templates/the_list/form_eror.html
{% if form.errors %}
<div class="alert alert-danger form-eror mt-2">
  {% for field, errors in form.errors.items %}
  {{ field }}: {{ errors|join:", " }}<br>
  {% endfor %}
</div>
{% endif %}

templates/the_list/index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
<div class="row">

  {% if request.GET.q %}
    <h4>Результаты поиска</h4>
  {% endif %}

  {% if not products %}
    <h1>Тут пусто</h1>
  {% endif %}


  {% for product in products %}
  <!--      1 элемент покупки-->
  <div class="row border border-primary rounded">

    <!--            отправить в купленое-->
    <div class="col-md-1 d-flex align-items-center">
      <a class="btn btn-primary" href="{% url 'the_list:product_change_status' product.slug %}"
         role="button">Купил</a>
    </div>
    <!--          продукт-->
    <div class="col-md-6">
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action"
           aria-current="true" data-bs-toggle="modal" data-bs-target="#productDetailModal{{ product.id }}">
          <div class="d-flex w-100 justify-content-between">

            <h5 class="mb-1">
              {% filter truncatechars_html:15 %}{% autoescape off %}{% if product.headline %}{{ product.headline }}{% else %}{{ product.name }}{% endif %}{% endautoescape %}{% endfilter %}</h5>
            <small>Цена: {{ product.price }}</small>
            <small>{{ product.created|date:"d m Y" }}</small>
          </div>
          <p class="mb-1">
            {% autoescape off %}{% if product.bodyline %}{{ product.bodyline|truncatechars_html:54 }}{% else %}{{ product.description|truncatechars_html:54 }}{% endif %}{% endautoescape %}
          </p>
        </a>
      </div>
    </div>

    <!--          модальное окно detail-->
    {% include 'the_list/product_detail.html' %}
    <!--          конец модального окна detail-->


    <!--          3 кнопки-->
    <div class="col-md-5 d-flex align-items-center">

      <a class="btn btn-danger mx-auto" href="{% url 'the_list:product_remove' product.slug %}"
         role="button">Удалить</a>


      <a class="btn btn-success mx-auto" href="#" role="button"
        data-bs-toggle="modal" data-bs-target="#productChange{{ product.id }}">
        Изменить</a>
      {% include 'the_list/product_change.html' %}

<!--      картинка-->
      <a class="btn btn-warning mx-auto" href="#" role="button"
         data-bs-toggle="modal" data-bs-target="#imageModal{{ product.id }}">Изображение</a>

      <div class="modal fade" id="imageModal{{ product.id }}" tabindex="-1" aria-labelledby="imageModalLabel"
           aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="imageModalLabel">Изображение</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
              {% if product.image %}
                <img src="{{ product.image.url }}" alt="Изображение" class="img-fluid max-screen-image">
              {% else %}
                <img src="{% static 'image/one.jpg' %}" alt="Изображение" class="img-fluid max-screen-image">
              {% endif %}
            </div>
          </div>
        </div>
      </div>
<!--      конец картинки-->

    </div>

  </div>
  <!--        конец элемента покупки-->
  {% endfor %}
</div>

{% endblock %}

templates/the_list/list_history.html
{% extends 'base.html' %}


{% block main %}
<div class="row">
  <div class="row">
    <div class="col-md-6">
      <h5>
        История покупок:
      </h5>
    </div>
    <div class="col-md-6">
      <h5>
        <a class=" mx-auto" href="#"
           data-bs-toggle="modal" data-bs-target="#modalHistoryClean">
          Очистить историю полностью
        </a>
      </h5>

      <!-- Modal -->
      <div class="modal fade" id="modalHistoryClean" tabindex="-1" aria-labelledby="modalHistoryClean" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">

            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Подтвердите удаление истории</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-footer">
              <a class="btn btn-primary me-auto" href="{% url 'product:product_history_clean' %}"
               role="button">Да, удалить</a>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>

          </div>
        </div>
      </div>
<!--      end modal-->
    </div>
  </div>

  {% if request.GET.q %}
    <h4>Результаты поиска</h4>
  {% endif %}

  {% if not products %}
    <h1>Тут пусто</h1>
  {% endif %}

  {% for product in products %}
  <!--      1 элемент покупки-->
  <div class="row border border-primary rounded">

    <!--          продукт-->
    <div class="col-md-6">
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action"
           aria-current="true" data-bs-toggle="modal" data-bs-target="#productDetailModal{{ product.id }}">
          <div class="d-flex w-100 justify-content-between">

            <h5 class="mb-1">
              {% filter truncatechars_html:15 %}{% autoescape off %}{% if product.headline %}{{ product.headline }}{% else %}{{ product.name }}{% endif %}{% endautoescape %}{% endfilter %}</h5>
            <small>Цена: {{ product.price }}</small>
          </div>
          <p class="mb-1">
            {% autoescape off %}{% if product.bodyline %}{{ product.bodyline|truncatechars_html:54 }}{% else %}{{ product.description|truncatechars_html:54 }}{% endif %}{% endautoescape %}
          </p>
        </a>
      </div>
    </div>

    <div class="col-md-6">
      <div class="row">
        <div class="col">
          <small>Создан: {{ product.created|date:"d m Y H:i:s" }}</small>
          <p>
            <small>Куплен: {{ product.buy_date|date:"d m Y H:i:s" }}</small>
          </p>

        </div>
        <div class="col d-flex align-items-center">
          <a class="btn btn-danger mx-auto" href="{% url 'the_list:product_remove' product.slug %}"
             role="button">Удалить из истории</a>

        </div>
      </div>

    </div>

    <!--          модальное окно detail-->
    {% include 'the_list/product_detail.html' %}
    <!--          конец модального окна detail-->

  </div>
  <!--        конец элемента покупки-->
  {% endfor %}
</div>

{% endblock%}

templates/the_list/messages.html
{% if messages %}
<div class="messages mt-2">
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

templates/the_list/product_add.html
<div class="col-md-12">

  <form action="{% url 'product:product_add' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}


    <div class="row">
      <h5>Добавить продукт</h5>
    </div>
    <div class="row">
      <div class="col-md-6">
        <label for="id_name" class="form-label">Заголовок покупки:</label>
        <input type="text" class="form-control" id="id_name"
               value="{% if form.name.value %}{{ form.name.value }}{% endif %}"
               name="name" required>
      </div>

      <div class="col-md-6">
        <label for="id_price" class="form-label">Цена:</label>
        <input type="number" step="0.01" class="form-control" id="id_price"
               value="{% if form.price.value %}{{ form.price.value }}{% endif %}"
               name="price"
               min="0.00" max="999999.99" style="width: 150px;">
      </div>

    </div>


    <div class="mb-3">
      <label for="{{ form.description.id_for_label }}" class="col-form-label">Описание:</label>
      <textarea class="form-control" id="{{ form.description.id_for_label }}"
                name="description"
                style="height: 150px;"></textarea>
    </div>

    <div class="mb-3">
      <input type="file" class="form-control" name="image" accept="image/*">
    </div>

    <div class="modal-footer">
      <button type="submit" class="btn btn-primary me-auto">Добавить покупку</button>
    </div>

  </form>

</div>

templates/the_list/product_change.html
{% load static %}
<div class="modal fade" id="productChange{{ product.id }}" tabindex="-1"
     aria-labelledby="productChangeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="productChangeModalLabel">Изменить - {{ product.name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row">

          <div class="col-md-6 border-end">

            <form action="{% url 'product:product_change' product.slug %}" method="POST" enctype="multipart/form-data">
              {% csrf_token %}

              <div class="row">
                <div class="col-md-6">
                  <label for="id_name" class="form-label">Заголовок покупки:</label>
                  <input type="text" class="form-control" id="id_name"
                         value="{{ product.name }}"
                         name="name" required>
                </div>

                <div class="col-md-6">
                  <label for="id_price" class="form-label">Цена:</label>
                  <input type="number" step="0.01" class="form-control" id="id_price"
                         value="{{ product.price }}"
                         name="price"
                         min="0.00" style="width: 150px;">
                </div>

              </div>

              <div class="mb-3">
                <label for="{{ form.description.id_for_label }}" class="col-form-label">Описание:</label>
                <textarea class="form-control" id="{{ form.description.id_for_label }}"
                          name="description"
                          style="height: 150px;">{{ product.description }}</textarea>
              </div>

              <div class="mb-3">
                <input type="file" class="form-control" id="id_image" name="image" accept="image/*">
              </div>
<!--              кнопку опустить вниз как то нада-->
              <div class="">
                <button type="submit" class="btn btn-primary">Изменить покупку</button>
              </div>

            </form>

          </div>

          <div class="col-md-6 text-center">
            {% if product.image %}
            <img src="{{ product.image.url }}"
                 alt="Картинка" class="img-thumbnail"
                 style="max-width: 500px; max-height: 500px">
            {% else %}
            <img src="{% static 'image/one.jpg' %}"
                 alt="Картинка" class="img-thumbnail"
                 style="max-width: 500px; max-height: 500px">
            {% endif %}
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

templates/the_list/product_detail.html
{% load static %}

<div class="modal fade" id="productDetailModal{{ product.id }}" tabindex="-1"
     aria-labelledby="productDetailModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="productDetailModalLabel">{{ product.name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row">

          <div class="col-md-6 border-end d-flex flex-column">
            <p>{{ product.description }}</p>
            <p>Цена: {{ product.price }} RUB</p>

            <div class="mt-auto">
              <p><small>Создан: {{ product.created|date:"d m Y H:i:s" }}</small></p>
              <p><small>Обновлен: {{ product.updated|date:"d m Y H:i:s" }}</small></p>
            </div>
          </div>

          <div class="col-md-6 text-center">
            {% if product.image %}
            <img src="{{ product.image.url }}"
                 alt="Картинка" class="img-thumbnail"
                 style="max-width: 400px;">
            {% else %}
            <img src="{% static 'image/one.jpg' %}"
                 alt="Картинка" class="img-thumbnail"
                 style="max-width: 400px;">
            {% endif %}
          </div>

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>